name: ${project.name}
main: jp.azisaba.lgw.kdstatus.KDStatusReloaded
version: ${project.version}
authors: [siloneco, matsu1213, sysnote8main]
description: "KDStatus reloaded."
website: ${project.url}
api-version: 1.16
commands:
  mystatus:
    aliases: ["ms", "status", "st"]
    permission: kdstatusreloaded.command.mystatus
  kdstatus:
    alias: ["kds"]
    permission: kdstatusreloaded.command.kdstatus
permissions:
  mystatus.command.mystatus:
    default: true
  kdstatusreloaded.command.kdstatus:
    default: op