name: '${name}'
main: jp.azisaba.lgw.kdstatus.KDStatusReloaded
version: '${version}'
authors: [siloneco, matsu1213, sysnote8main]
description: "${description}"
website: '${websiteUrl}'
api-version: 1.16
commands:
  mystatus:
    aliases: ["ms", "status", "st"]
    permission: kdstatusreloaded.command.mystatus
  kdstatus:
    alias: ["kds"]
    permission: kdstatusreloaded.command.kdstatus
permissions:
  kdstatusreloaded.command.mystatus:
    default: true
  kdstatusreloaded.command.kdstatus:
    default: op
