name: ${project.name}
main: jp.azisaba.lgw.kdstatus.KDStatusReloaded
version: ${project.version}
author: siloneco
description: "KDStatus reloaded."
website: ${project.url}
commands:
  mystatus:
    aliases: ["ms", "status", "st"]
    permission: mystatus.command.mystatus
permissions:
  mystatus.command.mystatus:
    default: true