---
name: Build Test
"on": [push, workflow_dispatch]

jobs:
  build-test:
    name: Build with Java 8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "adopt"
          cache: "maven"
      - run: java -version
      - run: mvn --version
      - run: mvn -B package

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          path: /home/runner/work/KDStatusReloaded/KDStatusReloaded/target/
